### ISSUE TITLE
Act_4, Mapa mental, Daisy González Lita 

### ISSUE THREAD

**Issue by Daisy-GonzalezLita12** [SistemasTecTlaxiaco/actividad-4-mapa-mental-Daisy-GonzalezLita12#1]
Actividad 4
Mapa mental "Comunicación oral y escrita"
Daisy Gonzalez Lita, 1BS
[daisy_comunicación_oral.pdf](https://github.com/SistemasTecTlaxiaco/actividad-4-mapa-mental-Daisy-GonzalezLita12/files/9616742/daisy_comunicacion_oral.pdf)

**Comment by ErikCuevas03** [comment]
18, la visibilidad es un poco complicado debido al color intenso del mapa

**Comment by josealfredo79** [comment]
Bien hecho y revisado
